Test/prompt > develop merge
nemodleo/attentionx-icl pull request #12
Opened 2024-03-17 13:10 UTC by cookie1077

Files to Note :

1. renamed run files
sst2.py and sst5.py > the new run scripts 
the old scripts are renamed as sst2.py and sst5.py

2. base_inferencer
- model init code reduced to one line. 
3. random_retriever
- edited to replace=False 

4. prompt_template
5. ppl_inferencer
>> modified (added few init attributes)

and some more...

2024-03-18 18:18 UTC, DHdroid commented on data/.DS_Store
.DS_Store들 다 삭제하고 .gitignore에 추가해주세요~

2024-03-18 18:18 UTC, DHdroid commented on data_utils/create_traindata_sst5.py
> +with open('/output/train_label_sst5.jsonl', 'w') as f:
이거 path의도 된건가요? "/output/" 앞에 "." 이 빠진거 아닌지 확인부탁드려요

2024-03-18 18:18 UTC, DHdroid commented on iclx/inferencer/parent_inferencer.py
> +        ice_idx_list = [ [i] for i in range(len(r))]
`ice_idx_list = retriever.retrieve()` 로 수정해주세요~

2024-03-18 18:18 UTC, DHdroid commented on iclx/inferencer/parent_inferencer.py
> +            print(idx)
debugging 용 print 들 좀 정리부탁드립니다

2024-03-18 18:18 UTC, DHdroid commented on iclx/inferencer/ppl_inferencer.py
> +        #print('Printing ICE examples-------------')
debugging용 주석이나 print좀 정리해주세요!

2024-03-20 06:51 UTC, DHdroid commented on scripts/sst5.py
> +<<<<<<< HEAD:scripts/sst5.py
이것 좀 resolve 부탁드립니다..

2024-03-20 12:34 UTC, nemo-prnd commented on data_utils/create_traindata_sst5.py
> +from openicl import DatasetReader
iclx으로 바꿔주세요

2024-03-20 12:34 UTC, nemo-prnd commented on data_utils/create_traindata_sst5.py
> +inferencer = ParentInferencer.ParentInferencer(model_name='EleutherAI/gpt-j-6b')
EleutherAI/gpt-j-6b -> EleutherAI/gpt-j-6B
으로 바꿔주세요
vessl에 캐쉬되어진 네임입니다

2024-03-20 12:34 UTC, nemo-prnd commented on data_utils/create_traindata_sst5.py
> +from openicl import AccEvaluator
iclx 으로 바꿔주세요

2024-03-20 12:34 UTC, nemo-prnd commented on data_utils/data_aug_sst2.py
> +df = process_jsonl('data/sst2/train_spaced_sst2.jsonl', 'data/sst2/train_spaced_sst2.jsonl')
이후에도 사용하는 코드라면 args 받게끔하는게 좋아보입니다

2024-03-20 12:34 UTC, nemo-prnd commented on data_utils/data_aug_sst5.py
> +#vessl.init()
불필요한 주석은 정리 부탁드립니다

2024-03-20 12:34 UTC, nemo-prnd commented on data_utils/data_aug_sst5.py
> +    print(x)
꼭 출력해야하나요?

2024-03-20 12:34 UTC, nemo-prnd commented on data_utils/data_aug_sst5.py
> +with open('data/sst5/train_sst5.jsonl', 'r') as f2, open('data/sst5/train_label_sst5.jsonl', 'r') as f1:
hard code는 지양

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/inferencer/base_inferencer.py
> +        self.model = AutoModelForCausalLM.from_pretrained(model_name)
이렇게 되면 accerate 사용이 불가해보입니다

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/inferencer/parent_inferencer.py
> +    def __get_ppl(self, input_texts: List[str], mask_length=None):
parent ppl class에 __get_ppl() 이미 있습니다

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/inferencer/ppl_inferencer.py
> +            print('Printing LLM prompt -------------')
.

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/inferencer/ppl_inferencer.py
> +
.

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/retriever/base_retriever.py
> +                 labels: Optional[List] = None,
.

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/retriever/base_retriever.py
> +        self.labels = labels
self.label 사용하지 않고 있습니다

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/retriever/base_retriever.py
> +                 order: Optional[bool] = False
order 보다 조금 더 자세한 변수명은 어떨까요?

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/retriever/random_retriever.py
> +                 labels: Optional[List] = None,
사용하지 않음

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/retriever/random_retriever.py
> +                 order: Optional[bool] = False
사용하지 않음

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/retriever/random_retriever.py
> +            # idx_list = np.random.choice(num_idx, self.ice_num).tolist()
삭제

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/retriever/random_retriever.py
> +            idx_list = np.random.choice(num_idx, self.ice_num, replace=False).tolist() #!
주석 삭제

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/retriever/topk_retriever.py
> -import tqdm
삭제하지 말아주세요

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/retriever/topk_retriever.py
> -import tqdm
ㅠㅠ

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/utils/dataset_reader.py
> +                 input_columns: Union[List[str], str],
지원되는지 확인 되었을까요?

2024-03-20 12:34 UTC, nemo-prnd commented on iclx/utils/dataset_reader.py
> +                 output_column: Union[List[str], str],
지원되는지 확인 되었을까요?

2024-03-20 12:34 UTC, nemo-prnd commented on scripts/create_subj_train.py
> +vessl.init()
필수인가요?

2024-03-20 12:34 UTC, nemo-prnd commented on scripts/create_subj_train.py
> +    train_ds = Dataset.from_generator(gen, gen_kwargs={"file_path": "data/subj/train.jsonl"})
hard coded

2024-03-20 12:34 UTC, nemo-prnd commented on scripts/create_subj_train.py
> +    inferencer = ParentInferencer(model_name='EleutherAI/gpt-j-6b')
b -> B

2024-03-20 12:34 UTC, nemo-prnd commented on scripts/create_traindata_sst2.py
> +vessl.init()
.

2024-03-20 12:34 UTC, nemo-prnd commented on scripts/create_traindata_sst2.py
> +    train_ds = Dataset.from_generator(gen, gen_kwargs={"file_path": "data/sst2/train_sst2.jsonl"})
.

2024-03-20 12:34 UTC, nemo-prnd commented on scripts/create_traindata_sst2.py
> +    inferencer = ParentInferencer(model_name='EleutherAI/gpt-j-6b')
.

2024-03-20 12:34 UTC, nemo-prnd commented on scripts/sst2.py
> +vessl.init()
.

2024-03-20 12:34 UTC, nemo-prnd commented on scripts/sst5.py
> +vessl.init()
.

2024-03-20 12:34 UTC, nemo-prnd commented on scripts/sst5.py
> +    print(naive)
print -> logger (ex, https://github.com/Delgan/loguru)

2024-03-23 08:06 UTC, DHdroid commented on iclx/utils/prompt_template.py
> +        tp = self.template[str(label)] if isinstance(self.template, Dict) else self.template
전부 다 str로 통일하기

2024-03-23 14:31 UTC, DHdroid commented on iclx/retriever/topk_retriever.py
이건 왜 사라진건가요..?

2024-03-23 19:19 UTC, yoonichoi requested changes
제 것 이외에도 전반적으로 지적된 사항들을 보니 크게:
- 주석정리
- conflict resolve하면서 딸려온 애들 정리
- hard coding 정리
그 외 자잘한 것들인 것 같은데, hard coding 정리의 경우 추후 merge할 universal train data generator + distill 파일에서 다루고 있으니 스킵해도 되지않을까싶네요. (이 PR에 사용되었던 train data gen, KD 파일들은 아카이빙하고)

2024-03-23 19:19 UTC, yoonichoi commented on iclx/retriever/topk_retriever.py
이거 다시 살려야할듯해요.. 회의 때 얘기하겠지만 main iclx랑 test/prompt iclx state가 달라서 topk retirever사용이 안되었네요

2024-03-23 19:19 UTC, yoonichoi commented on scripts/create_subj_train.py
> +    train_ds = Dataset.from_generator(gen, gen_kwargs={"file_path": "data/subj/train.jsonl"})
추후 PR인 create_data파일에서 hardcoding 부분해결되었습니다

2024-03-23 19:19 UTC, yoonichoi commented on scripts/sst2.py
> +    plt.savefig('/output/sst2.png')
이 output directory가 있다는 가정하에 savefig 하는건가요? 제가 돌렸을때는 이 부분에서 에러떴어서 vessl experiment에서만 가능한 세팅인지 궁금합니다. (이후 PR인 distill.py에서는 따로 parent directory에 output 폴더를 만들어 거기 저장하도록 하긴했습니다.) 생성되는 파일들 저장/관리를 어떻게 할 지에 관한 논의도 필요해보입니다

2024-03-23 19:19 UTC, yoonichoi commented on scripts/sst2.py
> +<<<<<<< HEAD:scripts/sst2.py
이부분은 commit revert하면서 딸려온 부분인것같은데 정리가 필요해보이네요

2024-03-23 19:19 UTC, yoonichoi commented on scripts/sst2.py
> +>>>>>>> 04fc83f5973c8b42adfec1667f358953e9b66e16:scripts/sst2_old.py
conflict resolve할때 딸려온 부분 정리

2024-03-23 19:19 UTC, yoonichoi commented on scripts/sst2.py
>      # assert score == {'accuracy': 0.5090609555189456}
assertion line 없애도 될듯합니다

2024-03-23 19:19 UTC, yoonichoi commented on scripts/sst2.py
> +>>>>>>> 04fc83f5973c8b42adfec1667f358953e9b66e16:scripts/sst2_old.py
정리

2024-03-24 04:36 UTC, cookie1077 commented on data/.DS_Store
추가했습니다!

2024-03-24 04:39 UTC, cookie1077 commented on data_utils/create_traindata_sst5.py
> +with open('/output/train_label_sst5.jsonl', 'w') as f:
vessl dir 상 절대 경로로 output 폴더에 접근하는 디렉토리입니다!

2024-03-24 05:13 UTC, cookie1077 commented on iclx/inferencer/base_inferencer.py
> +        self.model = AutoModelForCausalLM.from_pretrained(model_name)
저도 동의하는데 기존 openicl framework 에서는 그렇게 하더라고요
기존 OpenICL 코드에서 model_parallel 이 false 로 들어가는 것 같아요
근데 이상하게 두 경우에 실험 결과가 상당히 (!) 다르고 저렇게 하는게 결과가 훨씬 좋게 나와서 일단은 저렇게 뒀습니다!

2024-03-24 05:38 UTC, cookie1077 commented on iclx/retriever/base_retriever.py
> +                 order: Optional[bool] = False
use_ordering 으로 바꿨습니다.

2024-03-24 05:41 UTC, cookie1077 commented on iclx/utils/dataset_reader.py
> +                 input_columns: Union[List[str], str],
넵 작동은 해서 일단 남겨놓긴 했습니다..!

2024-03-24 05:41 UTC, cookie1077 commented on iclx/utils/dataset_reader.py
> +                 output_column: Union[List[str], str],
위와 같습니다.

2024-03-24 05:41 UTC, cookie1077 commented on scripts/create_subj_train.py
> +vessl.init()
옙 그래야 vessl exp 에서 output 저장이 가능합니다!

2024-03-24 05:43 UTC, cookie1077 commented on scripts/create_traindata_sst2.py
> +vessl.init()
여기도 동일하게 vessl 사용하려면 필요합니다

2024-03-24 05:48 UTC, cookie1077 commented on scripts/create_traindata_sst2.py
> +    train_ds = Dataset.from_generator(gen, gen_kwargs={"file_path": "data/sst2/train_sst2.jsonl"})
추후 pr 에서 data gen hard coded 부분 해결된 것 같습니다

2024-03-24 05:48 UTC, cookie1077 commented on scripts/sst5.py
> +vessl.init()
위와 같습니다

2024-03-24 06:01 UTC, cookie1077 commented on iclx/utils/prompt_template.py
> +        tp = self.template[str(label)] if isinstance(self.template, Dict) else self.template
generate_ice_item 이 inference 랑 ice prompt 다 받아야합니다
안 바꾸면 버그 나더라고용

2024-03-24 06:03 UTC, cookie1077 commented on scripts/sst2.py
> +    plt.savefig('/output/sst2.png')
vessl experiment 돌릴때 자체 output dir 가 있어서 그렇게 했는데 추후에 어떻게 할지 논의해보면 좋을 것 같습니다..!

2024-03-24 06:17 UTC, cookie1077 commented on iclx/retriever/topk_retriever.py
> -import tqdm
헉 복구하겠습니다

2024-03-24 08:46 UTC, DHdroid commented on iclx/utils/prompt_template.py
> +        tp = self.template[str(label)] if isinstance(self.template, Dict) else self.template
저번 시간에 template에 들어가는 label이 str일 때도 있고 int일 때도 있어서 통일하자는 얘기가 있었고, 관련된 코멘트입니다.

2024-03-24 12:43 UTC, nemo-prnd commented on iclx/inferencer/parent_inferencer.py
> +        r = retriever.retrieve()
중복 아닌가요?

2024-03-24 14:50 UTC, DHdroid commented on iclx/inferencer/base_inferencer.py
> +        self.model = AutoModelForCausalLM.from_pretrained(model_name)
- float16 때문에 결과가 달라지는지 확인 필요
- 맞다면 기존 코드에서 float16만 float32로
- 아니라면 일단 진행시켜 (accelerate 안쓴다)

2024-03-24 14:53 UTC, DHdroid commented on scripts/create_subj_train.py
> +vessl.init()
vessl.init() 다 삭제부탁드립니다!

2024-03-24 15:06 UTC, yoonichoi approved these changes

2024-03-27 14:16 UTC, nemodleo commented on iclx/inferencer/base_inferencer.py
> +        self.model = AutoModelForCausalLM.from_pretrained(model_name)
floating point에 의한 성능차이로 확인.
fp32 사용으로 결정

2024-03-27 14:22 UTC, nemodleo commented on iclx/retriever/topk_retriever.py
> +                 seed: Optional[int] = 43,
topk에 seed가 필요한가요?

2024-03-27 14:24 UTC, nemodleo commented on scripts/sst2.py
> +def test(shots=10, model_name='distilgpt2', retriever=TopkRetriever, seed=42, batch_size=1):
TopkRetriever 지원하는 sst2_topk.py 파일 따로 있습니다

2024-03-27 14:29 UTC, nemodleo commented on iclx/retriever/topk_retriever.py
> +                 seed: Optional[int] = 43,
seed argument 안 주는걸로(sst2_topk.py 참고), 
굳이  seed argument 주겠다 싶을 수 도 있기에 **kwargs 추가했습니다

2024-03-27 14:35 UTC, shovelingpig commented on data_utils/data_aug_sst2.py
> +    print(x)
debugging을 위해 넣었던 필요없는 print문은 빼야겠네요!

2024-03-27 14:36 UTC, shovelingpig commented on data_utils/data_aug_sst5.py
> +def rec_softmax(x):
이거는 엄청 자주 쓰이는데 utils에 하나 선언해두고 계속 import해서 쓰시죠.

여기저기서 3번 이상 같은 코드가 반복되면 utils로 만드는게 좋은 것 같아요.

2024-03-27 14:37 UTC, shovelingpig commented on iclx/inferencer/base_inferencer.py
> +        device_map = infer_auto_device_map(empty_model, dtype="float32")
이거 처음에 float16이었던 context가 어떻게 되나요? OpenICL이 float16을 썼나요?

2024-03-27 14:43 UTC, closed without merging